version: '2'

volumes:
  jenkins-home:
  gogs-data:
  db-data:
  nexus-data:

networks:
  nautsch.net:

services:
  nginxedge:
    image: jwilder/nginx-proxy
    container_name: nginx-edge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginxedge/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
    networks:
      nautsch.net:
        aliases:
          - ci.nautsch.net
          - git.nautsch.net
          - nexus.nautsch.net
          - registry.nautsch.net
          - aat.address.nautsch.net
          - uat.address.nautsch.net
          - extest.address.nautsch.net
          - demo.address.nautsch.net
          - address.nautsch.net
    restart: always

  ci:
    build:
      context: ./jenkins
    container_name: ci
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=ci.nautsch.net
      - VIRTUAL_PORT=8080
    volumes:
      - jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      nautsch.net:
    restart: always

  git:
    image: gogs/gogs:0.9.113
    container_name: git
    dns_search: .
    ports:
      - "10080:3000"
    environment:
      - VIRTUAL_HOST=git.nautsch.net
      - VIRTUAL_PORT=3000
    volumes:
      - gogs-data:/data
      - ./gogs/data/gogs/conf/app.ini:/data/gogs/conf/app.ini
    domainname: nautsch.net
    links:
      - db
    networks:
      nautsch.net:
    restart: always

  db:
    build:
      context: ./db
    container_name: db
    hostname: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      nautsch.net:
        aliases:
          - db.nautsch.net
    restart: always

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=nexus.nautsch.net
      - VIRTUAL_PORT=8081
    volumes:
      - nexus-data:/nexus-data
    networks:
      nautsch.net:
    restart: always

  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      - VIRTUAL_HOST=registry.nautsch.net
      - VIRTUAL_PORT=5000
    networks:
      nautsch.net:
    restart: always
